apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  url: https://argocd.kind.localhost
  #oidc.tls.insecure.skip.verify: true
  oidc.config: |
    name: Azure
    issuer: $oidc.azure:issuer
    clientID: $oidc.azure:clientID
    clientSecret: $oidc.azure:clientSecret
    requestedScopes: ["openid", "profile", "email"]
    requestedIDTokenClaims: {"groups": {"essential": true}}